# Generated by Django 2.2.4 on 2019-08-28 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_auto_20190827_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='usuario',
            field=models.CharField(max_length=50, unique=True, verbose_name='Usuario'),
        ),
    ]
