# Generated by Django 2.2.4 on 2019-08-29 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_auto_20190827_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='usuario',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
